In [75]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [76]:
train_ds = pd.read_csv('../datasets/fraudTrain.csv')
test_ds = pd.read_csv('../datasets/fraudTest.csv')

In [77]:
print(f'Train Dataset Shape: {train_ds.shape}\nTest Dataset Shape: {test_ds.shape}')

Train Dataset Shape: (1296675, 23)
Test Dataset Shape: (555719, 23)

In [78]:
train_ds.head(3)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0

In [79]:
test_ds.head(3)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0

In [80]:
train_ds.columns == test_ds.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [81]:
cols = train_ds.columns

cols

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='str')

In [82]:
train_ds.describe(include='all')

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1296675,1.296675e+06,1296675,1296675,1.296675e+06,1296675,1296675,1296675,1296675,1296675,1296675,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1296675,1296675,1296675,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
unique,NaN,1274791,NaN,693,14,NaN,352,481,2,983,894,51,NaN,NaN,NaN,NaN,494,968,1296675,NaN,NaN,NaN,NaN
top,NaN,2019-04-22 16:02:01,NaN,fraud_Kilback LLC,gas_transport,NaN,Christopher,Smith,F,864 Reynolds Plains,Birmingham,TX,NaN,NaN,NaN,NaN,Film/video editor,1977-03-23,0b242abb623afc578575680df30655b9,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,4403,131659,NaN,26669,28794,709863,3123,5617,94876,NaN,NaN,NaN,NaN,9779,5636,1,NaN,NaN,NaN,NaN
mean,6.483370e+05,NaN,4.171920e+17,NaN,NaN,7.035104e+01,NaN,NaN,NaN,NaN,NaN,NaN,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,NaN,NaN,NaN,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,NaN,1.308806e+18,NaN,NaN,1.603160e+02,NaN,NaN,NaN,NaN,NaN,NaN,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,NaN,NaN,NaN,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,NaN,6.041621e+10,NaN,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,NaN,NaN,NaN,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,NaN,1.800429e+14,NaN,NaN,9.650000e+00,NaN,NaN,NaN,NaN,NaN,NaN,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,NaN,NaN,NaN,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,NaN,3.521417e+15,NaN,NaN,4.752000e+01,NaN,NaN,NaN,NaN,NaN,NaN,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,NaN,NaN,NaN,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,NaN,4.642255e+15,NaN,NaN,8.314000e+01,NaN,NaN,NaN,NaN,NaN,NaN,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,NaN,NaN,NaN,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,NaN,4.992346e+18,NaN,NaN,2.894890e+04,NaN,NaN,NaN,NaN,NaN,NaN,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,NaN,NaN,NaN,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [83]:
test_ds.describe(include='all')

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
count,555719.000000,555719,5.557190e+05,555719,555719,555719.000000,555719,555719,555719,555719,555719,555719,555719.000000,555719.000000,555719.000000,5.557190e+05,555719,555719,555719,5.557190e+05,555719.000000,555719.000000,555719.000000
unique,NaN,544760,NaN,693,14,NaN,341,471,2,924,849,50,NaN,NaN,NaN,NaN,478,910,555719,NaN,NaN,NaN,NaN
top,NaN,2020-10-05 19:37:49,NaN,fraud_Kilback LLC,gas_transport,NaN,Christopher,Smith,F,444 Robert Mews,Birmingham,TX,NaN,NaN,NaN,NaN,Film/video editor,1977-03-23,2da90c7d74bd46a0caf3777415b3ebd3,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,1859,56370,NaN,11443,12146,304886,1474,2423,40393,NaN,NaN,NaN,NaN,4119,2408,1,NaN,NaN,NaN,NaN
mean,277859.000000,NaN,4.178387e+17,NaN,NaN,69.392810,NaN,NaN,NaN,NaN,NaN,NaN,48842.628015,38.543253,-90.231325,8.822189e+04,NaN,NaN,NaN,1.380679e+09,38.542798,-90.231380,0.003860
std,160422.401459,NaN,1.309837e+18,NaN,NaN,156.745941,NaN,NaN,NaN,NaN,NaN,NaN,26855.283328,5.061336,13.721780,3.003909e+05,NaN,NaN,NaN,5.201104e+06,5.095829,13.733071,0.062008
min,0.000000,NaN,6.041621e+10,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1257.000000,20.027100,-165.672300,2.300000e+01,NaN,NaN,NaN,1.371817e+09,19.027422,-166.671575,0.000000
25%,138929.500000,NaN,1.800429e+14,NaN,NaN,9.630000,NaN,NaN,NaN,NaN,NaN,NaN,26292.000000,34.668900,-96.798000,7.410000e+02,NaN,NaN,NaN,1.376029e+09,34.755302,-96.905129,0.000000
50%,277859.000000,NaN,3.521417e+15,NaN,NaN,47.290000,NaN,NaN,NaN,NaN,NaN,NaN,48174.000000,39.371600,-87.476900,2.408000e+03,NaN,NaN,NaN,1.380762e+09,39.376593,-87.445204,0.000000
75%,416788.500000,NaN,4.635331e+15,NaN,NaN,83.010000,NaN,NaN,NaN,NaN,NaN,NaN,72011.000000,41.894800,-80.175200,1.968500e+04,NaN,NaN,NaN,1.385867e+09,41.954163,-80.264637,0.000000
max,555718.000000,NaN,4.992346e+18,NaN,NaN,22768.110000,NaN,NaN,NaN,NaN,NaN,NaN,99921.000000,65.689900,-67.950300,2.906700e+06,NaN,NaN,NaN,1.388534e+09,66.679297,-66.952026,1.000000

In [84]:
train_ds.info(verbose=True, show_counts=True, memory_usage=True)

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  str
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  str
 4   category               1296675 non-null  str
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  str
 7   last                   1296675 non-null  str
 8   gender                 1296675 non-null  str
 9   street                 1296675 non-null  str
 10  city                   1296675 non-null  str
 11  state                  1296675 non-null  str
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  str
 17  dob                    1296675 non-null  str
 18  trans_num              1296675 non-null  str
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), str(12)
memory usage: 227.5 MB

In [85]:
# Convert transaction date and time from  str to pandas datetime.

cnv_dates = ['trans_date_trans_time', 'dob']

for date in cnv_dates:
    train_ds[date] = pd.to_datetime(train_ds[date])
    test_ds[date] = pd.to_datetime(test_ds[date])

train_ds[cnv_dates].info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 2 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  datetime64[us]
 1   dob                    1296675 non-null  datetime64[us]
dtypes: datetime64[us](2)
memory usage: 19.8 MB

In [86]:
test_ds[cnv_dates].info()

<class 'pandas.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 2 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  datetime64[us]
 1   dob                    555719 non-null  datetime64[us]
dtypes: datetime64[us](2)
memory usage: 8.5 MB

In [87]:
test_ds.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  datetime64[us]
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  str
 4   category               555719 non-null  str
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  str
 7   last                   555719 non-null  str
 8   gender                 555719 non-null  str
 9   street                 555719 non-null  str
 10  city                   555719 non-null  str
 11  state                  555719 non-null  str
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  str
 17  dob                    555719 non-null  datetime64[us]
 18  trans_num              555719 non-null  str
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: datetime64[us](2), float64(5), int64(6), str(10)
memory usage: 97.5 MB

In [88]:
train_ds.dtypes == test_ds.dtypes

Unnamed: 0               True
trans_date_trans_time    True
cc_num                   True
merchant                 True
category                 True
amt                      True
first                    True
last                     True
gender                   True
street                   True
city                     True
state                    True
zip                      True
lat                      True
long                     True
city_pop                 True
job                      True
dob                      True
trans_num                True
unix_time                True
merch_lat                True
merch_long               True
is_fraud                 True
dtype: bool

In [89]:
train_ds['is_fraud'].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [90]:
print(f"Fraud Percentage: {train_ds['is_fraud'].mean() * 100:.3f}%")

Fraud Percentage: 0.579%

In [91]:
test_ds['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

In [92]:
print(f"Fraud Percentage: {test_ds['is_fraud'].mean() * 100:.3f}%")

Fraud Percentage: 0.386%

### Missing Value Count

In [93]:
train_ds.isna().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [94]:
test_ds.isna().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

### Sorting Data.

- Sorting data by the card numbers and their respective transaction dates and times

In [95]:
new_train_ds = train_ds.copy()

sort_by = ['cc_num', 'trans_date_trans_time']

def sort_data(data, sort_by):
     return data.sort_values(sort_by).reset_index(drop=True)

new_train_ds = sort_data(new_train_ds, sort_by)

new_train_ds.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,1017,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,98e3dcf98101146a577f85a34e58feec,1325422035,43.974711,-109.741904,0
1,2724,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,498120fc45d277f7c88e3dba79c33865,1325493897,42.018766,-109.044172,0
2,2726,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,95f514bb993151347c7acdf8505c3d62,1325494056,42.961335,-109.157564,0
3,2882,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,4f0c1a14e0aa7eb56a490780ef9268c5,1325507894,42.228227,-108.747683,0
4,2907,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,3b2ebd3af508afba959640893e1e82bc,1325509846,43.321745,-108.091143,0

In [96]:
test_ds = sort_data(test_ds, sort_by)

test_ds.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,157,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,f21e1a09f59c50a66735409308285b1d,1371819942,42.945526,-108.530901,0
1,741,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,08f67c9765438973006f8250351d8c1f,1371831936,42.193130,-108.682054,0
2,3047,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,ca1f04d9d549c507356ffa8f9b43d81f,1371887913,43.932724,-109.699794,0
3,4351,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,d671d98fded8ca75d799959a444577a5,1371915151,43.546064,-109.212939,0
4,7695,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,Mary,Diaz,F,9886 Anita Drive,Fort Washakie,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,86d346444b5b262159976aa4d8b64fbb,1371990534,42.876538,-109.333220,0

## DATA CLEANING

1. Remove columns that are not needed for the model training
   - During checkout, the team collects the following information for the customer and are used can be used to predict where a customer is **Fraud** or **Not Fraud**
   1. Card number (CC in the dataset)
   2. Address (Street, city, Zip Code, Country)
   3. Amount
   4. Name of customer (_Has low predictive value_)
   <!-- Silent Data collected -->
   5. Date and time
   6. Location of merchant
   7. Merchant name
   8. Location of customer

##### HAS NO IMPACT ON THE MODEL (Low predictabilty): and can be dropped

- 'Unnamed: 0',
- 'first' and 'last (PII)'
- 'job (To be discussed with compliance)'
- 'unix_time'
- 'trans_num'
- 'city (PII)'

##### _NB: Card Number, Dob, Card holder's location, Mechant's location are not directly fed into the model but can be used to derive certain details that can be used to train a better model._

_For Example_

- Card previous activities
- Distance between the cardholder and the mechant.
- Usual location of cardholder
- average amount of the card
- rate of purchases of the card etc

In [97]:
drop_cols = ['Unnamed: 0','first', 'last', 'trans_num','city', 'unix_time']

new_train_ds = new_train_ds.drop(columns=drop_cols)
test_ds = test_ds.drop(columns=drop_cols)

In [98]:
new_train_ds.columns == test_ds.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

### Feature Engineering

- Age of card holder
- hour of transactions (fraudsters tend to use cards at odd hours when the card owner may not be active)
- day of week (fraudsters are more likely to use the card during weekends than weekdays)
- distance_km (distance between card holder and mechant)
- card_txn_count_24h (number of transactions on this card in the trailing 24h (velocity).)
- rate - card_amt_mean / card_amt_std — the card's typical spend, so the model can spot a transaction that's abnormal for that card. Same past-only rule.
- amt_vs_card_mean

In [99]:
# Age
def calc_age(data, col='age'):
    data[col] = (new_train_ds['trans_date_trans_time'] - new_train_ds['dob']).dt.days // 365
    return data


new_train_ds = calc_age(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32

In [100]:
test_ds = calc_age(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32

In [101]:
# Hour and Day of transaction
def calc_hour_and_day(data):
    data['hour'] = data['trans_date_trans_time'].dt.hour
    data['day'] = data['trans_date_trans_time'].dt.day

    return data

new_train_ds = calc_hour_and_day(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2

In [102]:
test_ds = calc_hour_and_day(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23

In [103]:
# Distance in kilometers
def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371
    # convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    return R * 2 * np.arcsin(np.sqrt(a))

new_train_ds["distance_km"] = haversine_km(
    new_train_ds["lat"], new_train_ds["long"],
    new_train_ds["merch_lat"], new_train_ds["merch_long"]
)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965

In [104]:
test_ds["distance_km"] = haversine_km(
    test_ds["lat"], test_ds["long"],
    test_ds["merch_lat"], test_ds["merch_long"]
)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273

In [105]:
# card_txn_count_24h
def calc_card_txn_count_24h(data, col='card_txn_count_24h'):
  data[col] = (
      data.set_index("trans_date_trans_time")
        .groupby("cc_num")["amt"]
        .rolling("24h", closed="left")
        .count()
        .values
  )

  return data

new_train_ds = calc_card_txn_count_24h(new_train_ds).fillna(0)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0

In [106]:
test_ds = calc_card_txn_count_24h(test_ds).fillna(0)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0

In [107]:
new_train_ds["card_txn_count_24h"].describe(include='all')

count    1.296675e+06
mean     3.884149e+00
std      3.082097e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      3.500000e+01
Name: card_txn_count_24h, dtype: float64

In [108]:
test_ds["card_txn_count_24h"].describe(include='all')

count    555719.000000
mean          4.625877
std           3.573342
min           0.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          35.000000
Name: card_txn_count_24h, dtype: float64

In [109]:
# card_amt_mean
def calc_card_amt_mean(data, col='card_amt_mean'):
    data["card_amt_mean"] = (
        data
        .groupby("cc_num")["amt"]
        .transform(lambda s: s.shift().expanding().mean())
    ).fillna(data['amt'])

    return data

new_train_ds = calc_card_amt_mean(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0,7.270
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0,7.270
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0,30.105
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0,47.430
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0,44.270

In [110]:
test_ds = calc_card_amt_mean(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0,124.660000
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0,124.660000
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0,101.590000
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0,89.476667
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0,89.042500

In [111]:
# card_amt_mean
def calc_card_amt_std(data, col='card_amt_std'):
    data[col] = (
        data
        .groupby('cc_num')['amt']
        .transform(lambda s: s.shift().expanding().std())
    ).fillna(0)

    return data

new_train_ds = calc_card_amt_std(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0,7.270,0.000000
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0,7.270,0.000000
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0,30.105,32.293567
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0,47.430,37.708144
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0,44.270,31.430534

In [112]:
test_ds = calc_card_amt_std(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0,124.660000,0.000000
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0,124.660000,0.000000
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0,101.590000,32.625907
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0,89.476667,31.183705
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0,89.042500,25.476191

In [113]:
def rate(data, col='rate'):
    rate = new_train_ds['card_amt_mean'] / (new_train_ds['card_amt_std'])
    data[col] = rate.replace([np.inf, -np.inf], np.nan).fillna(0)
    
    return data

In [114]:
new_train_ds = rate(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0,7.270,0.000000,0.000000
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0,7.270,0.000000,0.000000
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0,30.105,32.293567,0.932229
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0,47.430,37.708144,1.257818
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0,44.270,31.430534,1.408503

In [115]:
test_ds = rate(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0,124.660000,0.000000,0.000000
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0,124.660000,0.000000,0.000000
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0,101.590000,32.625907,0.932229
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0,89.476667,31.183705,1.257818
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0,89.042500,25.476191,1.408503

In [116]:
# amt_vs_card_mean

def calc_amt_vs_card_mean(data, col='amt_vs_card_mean'):
    mean = data['card_amt_mean'].replace([np.inf, -np.inf], np.nan).fillna(0)
    data[col] = data['amt'] / mean
    
    return data

new_train_ds = calc_amt_vs_card_mean(new_train_ds)

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate,amt_vs_card_mean
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0,7.270,0.000000,0.000000,1.000000
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0,7.270,0.000000,0.000000,7.281981
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0,30.105,32.293567,0.932229,2.726457
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0,47.430,37.708144,1.257818,0.733502
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0,44.270,31.430534,1.408503,0.613960

In [117]:
test_ds = calc_amt_vs_card_mean(test_ds)

test_ds.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate,amt_vs_card_mean
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,home,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0,124.660000,0.000000,0.000000,1.000000
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,misc_pos,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0,124.660000,0.000000,0.000000,0.629873
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,gas_transport,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0,101.590000,32.625907,0.932229,0.642288
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,kids_pets,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0,89.476667,31.183705,1.257818,0.980591
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,personal_care,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0,89.042500,25.476191,1.408503,1.662352

In [118]:
new_train_ds.columns == test_ds.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [119]:
new_train_ds[['category','merchant', 'state']].describe(include='all')

             category           merchant    state
count         1296675            1296675  1296675
unique             14                693       51
top     gas_transport  fraud_Kilback LLC       TX
freq           131659               4403    94876

In [120]:
test_ds[['category','merchant', 'state']].describe(include='all')

             category           merchant   state
count          555719             555719  555719
unique             14                693      50
top     gas_transport  fraud_Kilback LLC      TX
freq            56370               1859   40393

### Encoding

- Merchant: > 15 :Frequency encoding
- State: > 15: Frequency encoding
- Category: < 15: One-hot encoding

In [121]:
# One Hot Encoding Category
new_train_ds = pd.get_dummies(new_train_ds, columns=['category'], drop_first=True)
test_ds = pd.get_dummies(test_ds, columns=['category'], drop_first=True)

In [122]:
# Frequency Encoding
# def frequency_enc(data, col):
#     freq = data[col].value_counts
#     return data[col].map(freq).fillna(0)

# new_train_ds['mechant_enc'] = frequency_enc(new_train_ds, 'merchant')

In [123]:
def freq_enc(data, target_col, col_name):
    freq = data[target_col].value_counts()
    data[col_name] = data[target_col].map(freq)

    return data

In [124]:
new_train_ds = freq_enc(new_train_ds, 'merchant', 'merchant_enc')
new_train_ds = freq_enc(new_train_ds, 'state', 'state_enc')

new_train_ds.head()

,trans_date_trans_time,cc_num,merchant,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate,amt_vs_card_mean,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_enc,state_enc
0,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",7.27,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.974711,-109.741904,0,32,12,1,127.606239,0.0,7.270,0.000000,0.000000,1.000000,False,False,False,False,False,False,False,True,False,False,False,False,False,1269,19322
1,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,52.94,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.018766,-109.044172,0,32,8,2,110.308921,1.0,7.270,0.000000,0.000000,7.281981,False,True,False,False,False,False,False,False,False,False,False,False,False,2677,19322
2,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,82.08,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.961335,-109.157564,0,32,8,2,21.787261,2.0,30.105,32.293567,0.932229,2.726457,False,True,False,False,False,False,False,False,False,False,False,False,False,2630,19322
3,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,34.79,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.228227,-108.747683,0,32,12,2,87.204215,3.0,47.430,37.708144,1.257818,0.733502,False,False,False,False,False,False,True,False,False,False,False,False,False,2230,19322
4,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,27.18,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.321745,-108.091143,0,32,13,2,74.212965,3.0,44.270,31.430534,1.408503,0.613960,False,False,False,False,False,True,False,False,False,False,False,False,False,2473,19322

In [125]:
test_ds = freq_enc(test_ds, 'merchant', 'merchant_enc')
test_ds = freq_enc(test_ds, 'state', 'state_enc')

test_ds.head()

,trans_date_trans_time,cc_num,merchant,amt,gender,street,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate,amt_vs_card_mean,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_enc,state_enc
0,2020-06-21 13:05:42,60416207185,fraud_Kutch-Ferry,124.66,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.945526,-108.530901,0,32,13,21,30.457093,0.0,124.660000,0.000000,0.000000,1.000000,False,False,False,False,False,True,False,False,False,False,False,False,False,1036,8454
1,2020-06-21 16:25:36,60416207185,fraud_Halvorson Group,78.52,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.193130,-108.682054,0,32,16,21,91.942935,1.0,124.660000,0.000000,0.000000,0.629873,False,False,False,False,False,False,False,False,True,False,False,False,False,715,8454
2,2020-06-22 07:58:33,60416207185,fraud_Conroy-Cruickshank,65.25,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.932724,-109.699794,0,32,7,22,121.857420,2.0,101.590000,32.625907,0.932229,0.642288,False,True,False,False,False,False,False,False,False,False,False,False,False,1119,8454
3,2020-06-22 15:32:31,60416207185,fraud_Larkin Ltd,87.74,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,43.546064,-109.212939,0,32,15,22,65.414164,2.0,89.476667,31.183705,1.257818,0.980591,False,False,False,False,False,False,True,False,False,False,False,False,False,927,8454
4,2020-06-23 12:28:54,60416207185,fraud_Leffler-Goldner,148.02,F,9886 Anita Drive,WY,82514,43.0048,-108.8964,1645,Information systems manager,1986-02-17,42.876538,-109.333220,0,32,12,23,38.311273,1.0,89.042500,25.476191,1.408503,1.662352,False,False,False,False,False,False,False,False,False,True,False,False,False,775,8454

In [126]:
# Drop all columns that are not usable

drop_cols = [
    'trans_date_trans_time', 'cc_num', 'merchant', 'state',
    'gender', 'street', 'zip', 'job',
    'lat', 'long', 'merch_lat', 'merch_long', 'dob',
]

new_train_ds = new_train_ds.drop(columns=drop_cols)

In [127]:
new_train_ds.columns

Index(['amt', 'city_pop', 'is_fraud', 'age', 'hour', 'day', 'distance_km',
       'card_txn_count_24h', 'card_amt_mean', 'card_amt_std', 'rate',
       'amt_vs_card_mean', 'category_food_dining', 'category_gas_transport',
       'category_grocery_net', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_misc_pos', 'category_personal_care',
       'category_shopping_net', 'category_shopping_pos', 'category_travel',
       'merchant_enc', 'state_enc'],
      dtype='str')

In [128]:
new_train_ds.shape

(1296675, 27)

In [129]:
new_train_ds.head()

,amt,city_pop,is_fraud,age,hour,day,distance_km,card_txn_count_24h,card_amt_mean,card_amt_std,rate,amt_vs_card_mean,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_enc,state_enc
0,7.27,1645,0,32,12,1,127.606239,0.0,7.270,0.000000,0.000000,1.000000,False,False,False,False,False,False,False,True,False,False,False,False,False,1269,19322
1,52.94,1645,0,32,8,2,110.308921,1.0,7.270,0.000000,0.000000,7.281981,False,True,False,False,False,False,False,False,False,False,False,False,False,2677,19322
2,82.08,1645,0,32,8,2,21.787261,2.0,30.105,32.293567,0.932229,2.726457,False,True,False,False,False,False,False,False,False,False,False,False,False,2630,19322
3,34.79,1645,0,32,12,2,87.204215,3.0,47.430,37.708144,1.257818,0.733502,False,False,False,False,False,False,True,False,False,False,False,False,False,2230,19322
4,27.18,1645,0,32,13,2,74.212965,3.0,44.270,31.430534,1.408503,0.613960,False,False,False,False,False,True,False,False,False,False,False,False,False,2473,19322

In [130]:
test_ds = test_ds.drop(columns=drop_cols)

In [131]:
test_ds.columns

Index(['amt', 'city_pop', 'is_fraud', 'age', 'hour', 'day', 'distance_km',
       'card_txn_count_24h', 'card_amt_mean', 'card_amt_std', 'rate',
       'amt_vs_card_mean', 'category_food_dining', 'category_gas_transport',
       'category_grocery_net', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_misc_pos', 'category_personal_care',
       'category_shopping_net', 'category_shopping_pos', 'category_travel',
       'merchant_enc', 'state_enc'],
      dtype='str')

In [132]:
new_train_ds.columns == test_ds.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

### MODEL CREATION

In [133]:
X_train = new_train_ds.drop(columns=['is_fraud'])
y_train = new_train_ds['is_fraud']

In [134]:
X_test = test_ds.drop(columns=['is_fraud'])
y_test = test_ds['is_fraud']

In [135]:
print((X_train.columns == X_test.columns).all()) 
print(X_train.isna().sum().sum())

True
0

In [148]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [138]:
lg = LogisticRegression(max_iter=100000, class_weight='balanced',random_state=42)

lg.fit(X_train, y_train)

proba = lg.predict_proba(X_test)[:,1]
y_pred = (proba >= 0.3).astype(int)

print(classification_report(y_test, y_pred, digits=3))

c:\Users\Jefferson\anaconda3\envs\fraud\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 12774 iteration(s) (status=1):
STOP: TOTAL NO. OF F,G EVALUATIONS EXCEEDS LIMIT

You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           0      1.000     0.321     0.486    553574
           1      0.006     0.974     0.011      2145

    accuracy                          0.324    555719
   macro avg      0.503     0.648     0.249    555719
weighted avg      0.996     0.324     0.485    555719

In [ ]:
import lightgbm as lgb

In [146]:
print((y_train == 0).sum())
print((y_train == 1).sum())
print((y_train == 0).sum() / (y_train == 1).sum())

1289169
7506
171.75179856115108

In [145]:
(y_train == 1).sum()

np.int64(7506)

In [ ]:
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

model = lgb.LGBMClassifier(
    scale_pos_weight=100 #scale_pos_weight,
    n_estimators=2000,
    learning_rate=0.05,
    num_leaves=15,           # simpler trees
    min_child_samples=100,   # each leaf needs more data
    subsample=0.8, subsample_freq=1,
    colsample_bytree=0.8,
    reg_lambda=1.0,
)
model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    eval_metric="average_precision",
    callbacks=[lgb.early_stopping(100)], 
)
print('done')

c:\Users\Jefferson\anaconda3\envs\fraud\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Info] Number of positive: 7506, number of negative: 1289169
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.020981 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2277
[LightGBM] [Info] Number of data points in the train set: 1296675, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.005789 -> initscore=-5.146050
[LightGBM] [Info] Start training from score -5.146050
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[3]	valid_0's average_precision: 0.17353	valid_0's binary_logloss: 0.0952499
done

In [153]:
proba = lg.predict_proba(X_test)[:,1]
y_pred = (proba >= 0.2).astype(int)

print(classification_report(y_test, y_pred, digits=3))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0      1.000     0.150     0.262    553574
           1      0.005     0.999     0.009      2145

    accuracy                          0.154    555719
   macro avg      0.502     0.575     0.135    555719
weighted avg      0.996     0.154     0.261    555719

[[ 83310 470264]
 [     2   2143]]

In [158]:
train_proba = model.predict_proba(X_train)[:, 1]
test_proba  = model.predict_proba(X_test)[:, 1]

In [159]:
print("Train PR-AUC:", average_precision_score(y_train, train_proba))
print("Test  PR-AUC:", average_precision_score(y_test, test_proba))

Train PR-AUC: 0.2864208333676312
Test  PR-AUC: 0.17352977253667726

In [151]:
from sklearn.metrics import average_precision_score
pr_auc = average_precision_score(y_test, y_pred)
print(pr_auc)

0.004535711854001567